tehanbye_the_world:
    path:    /bye
    defaults: { _controller: TEHANDPlatformBundle:Bye:bye }
    
    # src/OC/PlatformBundle/Resources/config/routing.yml

tehan_platform_home:
    path:      /
    defaults: { _controller: TEHANDPlatformBundle:Advert:index }
    
tehan_platform_view:
    path:      /a/{id}
    defaults: { _controller: TEHANDPlatformBundle:Advert:view }
    
tehan_platform_view_slug:
    path:      /{year}/{slug}.{format}
    defaults:  
        _controller: TEHANDPlatformBundle:Advert:viewSlug 
        _format:    html
    requirements:
        year:    \d{4}
        _format:  html|xml
        _locale:  fr|en
    
tehan_platform_add:
    path:      /add
    defaults: { _controller: TEHANDPlatformBundle:Advert:add }