services:
    tehand_platform.antispam:
        class: TEHAND\PlatformBundle\Antispam\TehandAntispam
        arguments: 
            - "@mailer"
            - %locale%
            - 50
            
    tehand_platform.email.application_mailer:
        class: TEHAND\PlatformBundle\Email\ApplicationMailer
        arguments: 
            - "@mailer"
            
    tehand_platform.doctrine_listener.application_creation:
        class: TEHAND\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments: 
            - "@tehand_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }