<?php

namespace TEHAND\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function myFindAll() {
                
        $queryBuilder = $this->createQueryBuilder('a');
        
        $query = $queryBuilder->getQuery();
        
        $results = $query->getResult();
        
        return $results;
    }
    
}
