services:
    tehand_platform.antispam:
        class: TEHAND\PlatformBundle\Antispam\TehandAntispam
        arguments: 
            - "@mailer"
            - %locale%
            - 50
parameters:
    mon_parametre: ma_valeur